server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.application.name}?createDatabaseIfNotExist=true
    port: 3307
    host: localhost
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # only for testing
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true
  data:
    redis:
      host: localhost
      port: 6379
      cacheDuration: 10 # minutes
      password: root
      jedis:
        pool:
          enabled: true
          max-active: 8
          min-idle: 0
      connect-timeout: 10
  rabbitmq:
    host: localhost
    port: 5672
    username: root
    password: root
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

idv:
  labor-lab:
    id-counter-key: userId
    encryption:
      key: testingEncryptionKey1234   # length of key should be 16, 24 or 32
      initial-vector: initialVector
      authentication-tag-length: 128  # Must be one of {128, 120, 112, 104, 96}
      additional-authenticated-data: additionalAuthenticatedData