server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${spring.datasource.host}:${spring.datasource.port}/${spring.application.name}?createDatabaseIfNotExist=true
    port: 3307
    host: localhost
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop # only for testing
    database-platform: org.hibernate.dialect.MySQLDialect
    generate-ddl: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka