server:
  port: 8888

file:
  location:
    local: file://${user.home}/IdeaProjects
    GitHub: https://github.com/${git.username}
git:
  uri: ${file.location.GitHub}/${git.repo}
  repo: config-manager
  username: Maxence2997
  accessToken: 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
  branch: dev

spring:
  cloud:
    config:
      server:
        git:
          uri: ${git.uri}
          search-paths:
            - dev
          force-pull: true
          default-label: ${git.branch}
          username: ${git.username}
          password: ${git.accessToken}

eureka:
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka
# TODO write down the properties